Added backend dependencies

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -48,23 +48,23 @@ jobs:
           paths:
             - backend/node_modules
   
-  build-frontend:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout
-      - restore_cache:
-          keys: [frontend-build]
-      - run:
-          name: Build front-end
-          command: |
-            cd frontend
-            npm i
-            npm run build
-            exit 1
-      - save_cache:
-          paths: [frontend/node_modules]
-          key: frontend-build
+#  build-frontend:
+#    docker:
+#      - image: circleci/node:13.8.0
+#    steps:
+#      - checkout
+#      - restore_cache:
+#          keys: [frontend-build]
+#      - run:
+#          name: Build front-end
+#          command: |
+#            cd frontend
+#            npm i
+#            npm run build
+#            exit 1
+#      - save_cache:
+#          paths: [frontend/node_modules]
+#          key: frontend-build
 
   build-backend:
     docker:
@@ -84,202 +84,202 @@ jobs:
           paths: [backend/node_modules]
           key: backend-build
 
-  test-frontend:
-    docker:
-      # Docker image here
-    steps:
+#  test-frontend:
+#    docker:
+#      # Docker image here
+#    steps:
       # Checkout code from git
       # Restore from cache
       # Your job code here
                 
-  test-backend:
-    docker:
+#  test-backend:
+#    docker:
       # Docker image here
-    steps:
+#    steps:
       # Checkout code from git
       # Restore from cache
       # Your job code here
             
-  scan-frontend:
-    docker:
+#  scan-frontend:
+#    docker:
       # Docker image here
-    steps:
+#    steps:
       # Checkout code from git
       # Restore from cache
       # Your job code here
 
-  scan-backend:
-    docker:
+#  scan-backend:
+#    docker:
       # Docker image here
-    steps:
+#    steps:
       # Checkout code from git
       # Restore from cache
       # Your job code here
 
-  deploy-infrastructure:
-    docker:
+#  deploy-infrastructure:
+#    docker:
       # Docker image here that supports AWS CLI
-    steps:
+#    steps:
       # Checkout code from git
-      - run:
-          name: Ensure back-end infrastructure exists
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/backend.yml \
+#      - run:
+#          name: Ensure back-end infrastructure exists
+#          command: |
+#            aws cloudformation deploy \
+#              --template-file .circleci/files/backend.yml \
               #--tags project=your-tag \
               # --stack-name "your back-end stack name with workflow id" \
               # --parameter-overrides ID="your workflow id"  
-              exit 1
-      - run:
-          name: Ensure front-end infrastructure exist
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/frontend.yml \
+#              exit 1
+#      - run:
+#          name: Ensure front-end infrastructure exist
+#          command: |
+#            aws cloudformation deploy \
+#              --template-file .circleci/files/frontend.yml \
               #--tags project=your-tag \
               # --stack-name "your front-end stack name with workflow id" \
               # --parameter-overrides ID="your workflow id"  
-              exit 1
-      - run:
-          name: Add back-end ip to ansible inventory
-          command: |
+#              exit 1
+#      - run:
+#          name: Add back-end ip to ansible inventory
+#          command: |
             # Your code here
-            exit 1
-      - persist_to_workspace:
-          root: ~/
-          paths:
-            - project/.circleci/ansible/inventory.txt
+#            exit 1
+#      - persist_to_workspace:
+#          root: ~/
+#          paths:
+#            - project/.circleci/ansible/inventory.txt
       # Here's where you will add some code to rollback on failure      
 
-  configure-infrastructure:
-    docker:
+#  configure-infrastructure:
+#    docker:
       # Docker image here that supports Ansible
-    steps:
+#    steps:
       # Checkout code from git
       # Add ssh keys with fingerprint
       # attach workspace
-      - run:
-          name: Install dependencies
-          command: |
+#      - run:
+#          name: Install dependencies
+#          command: |
             # Your code here
-            exit 1
-      - run:
-          name: Configure server
-          command: |
+#            exit 1
+#      - run:
+#          name: Configure server
+#          command: |
             # Your code here
-            exit 1
+#            exit 1
       # Here's where you will add some code to rollback on failure      
 
-  run-migrations:
-    docker:
+#  run-migrations:
+#    docker:
       # Docker image here that supports NodeJS
-    steps:
+#    steps:
       # Checkout code from git
-      - run:
-          name: Run migrations
-          command: |
+#      - run:
+#          name: Run migrations
+#          command: |
             # Your code here
-            exit 1
-      - run:
-          name: Send migration results to memstash
-          command: |
-            # Your code here
-            exit 1
+#            exit 1
+#      - run:
+#          name: Send migration results to memstash
+#          command: |
+#            # Your code here
+#            exit 1
      # Here's where you will add some code to rollback on failure      
 
-  deploy-frontend:
-    docker:
+#  deploy-frontend:
+#    docker:
       # Docker image here that supports AWS CLI
-    steps:
+#    steps:
       # Checkout code from git
-      - run:
-          name: Install dependencies
-          command: |
+#      - run:
+#          name: Install dependencies
+#          command: |
             # your code here
-      - run:
-          name: Get backend url
-          command: |
+#      - run:
+#          name: Get backend url
+#          command: |
             # your code here
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"
-      - run:
-          name: Deploy frontend objects
-          command: |
+#            export API_URL="http://${BACKEND_IP}:3030"
+#            echo "${API_URL}"
+#      - run:
+#          name: Deploy frontend objects
+#          command: |
             # your code here
       # Here's where you will add some code to rollback on failure      
                     
-  deploy-backend:
-    docker:
+#  deploy-backend:
+#    docker:
       # Docker image here that supports Ansible
-    steps:
+#    steps:
       # Checkout code from git
       # Add ssh keys with fingerprint
       # attach workspace
-      - run:
-          name: Install dependencies
-          command: |
+#      - run:
+#          name: Install dependencies
+#          command: |
             # your code here
-      - run:
-          name: Deploy backend
-          command: |
-            # your code here
+#      - run:
+#          name: Deploy backend
+#          command: |
+#            # your code here
       # Here's where you will add some code to rollback on failure  
 
-  smoke-test:
-    docker:
+#  smoke-test:
+#    docker:
       # Lightweight Docker image 
-    steps:
+#    steps:
       # Checkout code from git
-      - run:
-          name: Install dependencies
-          command: |
+#      - run:
+#          name: Install dependencies
+#          command: |
             # your code here
-      - run:
-          name: Get backend url
-          command: |
+#      - run:
+#          name: Get backend url
+#          command: |
             # your code here
-      - run:
-          name: Backend smoke test.
-          command: |
+#      - run:
+#          name: Backend smoke test.
+#          command: |
             # your code here
-      - run:
-          name: Frontend smoke test.
-          command: |
+#      - run:
+#          name: Frontend smoke test.
+#          command: |
             # your code here
       # Here's where you will add some code to rollback on failure  
 
-  cloudfront-update:
-    docker:
+#  cloudfront-update:
+#    docker:
       # Docker image here that supports AWS CLI
-    steps:
+#    steps:
       # Checkout code from git
-      - run:
-          name: Install dependencies
-          command: |
+#      - run:
+#          name: Install dependencies
+#          command: |
             # your code here
-      - run:
-          name: Update cloudfront distribution
-          command: |
+#      - run:
+#          name: Update cloudfront distribution
+#          command: |
             # your code here
       # Here's where you will add some code to rollback on failure  
 
-cleanup:
-    docker:
+#cleanup:
+#    docker:
       # Docker image here
-    steps:
+#    steps:
       # Checkout code from git
-      - run:
-          name: Get old stack workflow id
-          command: |
+#      - run:
+#          name: Get old stack workflow id
+#          command: |
             # your code here
-            export OldWorkflowID="the id here"
-            export STACKS=[] #put the list of stacks here
-      - run:
-          name: Remove old stacks and files
-          command: |
-            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-            then
+#            export OldWorkflowID="the id here"
+#            export STACKS=[] #put the list of stacks here
+#      - run:
+#          name: Remove old stacks and files
+#          command: |
+#            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+#            then
               # your code here
-            fi
+#            fi
             
 
 workflows:
